ALTER TABLE CUSTOMER DROP FOREIGN KEY FK_CUSTOMER_USERNAME
ALTER TABLE TRAVELPACKAGE DROP FOREIGN KEY FK_TRAVELPACKAGE_idCustomerBuyer
ALTER TABLE CUSTOMIZEDTRAVELPACKAGE DROP FOREIGN KEY FK_CUSTOMIZEDTRAVELPACKAGE_idcustomer
ALTER TABLE CUSTOMIZEDTRAVELPACKAGE DROP FOREIGN KEY FK_CUSTOMIZEDTRAVELPACKAGE_IDTRAVELPACKAGE
ALTER TABLE EMPLOYEE DROP FOREIGN KEY FK_EMPLOYEE_code
ALTER TABLE EMPLOYEE DROP FOREIGN KEY FK_EMPLOYEE_USERNAME
ALTER TABLE PRODUCT DROP FOREIGN KEY FK_PRODUCT_idStage
ALTER TABLE PRODUCT DROP FOREIGN KEY FK_PRODUCT_idemployee
ALTER TABLE FLIGHT DROP FOREIGN KEY FK_FLIGHT_IDPRODUCT
ALTER TABLE GIFTLIST DROP FOREIGN KEY FK_GIFTLIST_idProduct
ALTER TABLE GIFTLIST DROP FOREIGN KEY FK_GIFTLIST_travelPackageFK
ALTER TABLE GIFTLIST DROP FOREIGN KEY FK_GIFTLIST_idCustomer
ALTER TABLE HOTEL DROP FOREIGN KEY FK_HOTEL_IDPRODUCT
ALTER TABLE OUTING DROP FOREIGN KEY FK_OUTING_IDPRODUCT
ALTER TABLE PREPACKEDTRAVELPACKAGE DROP FOREIGN KEY FK_PREPACKEDTRAVELPACKAGE_idEmployeeCreator
ALTER TABLE PREPACKEDTRAVELPACKAGE DROP FOREIGN KEY FK_PREPACKEDTRAVELPACKAGE_IDTRAVELPACKAGE
ALTER TABLE STAGE DROP FOREIGN KEY FK_STAGE_IDTRAVELPACKAGE
ALTER TABLE USER_GROUP DROP FOREIGN KEY FK_USER_GROUP_username
DROP TABLE CODE
DROP TABLE REGISTEREDUSER
DROP TABLE CUSTOMER
DROP TABLE TRAVELPACKAGE
DROP TABLE CUSTOMIZEDTRAVELPACKAGE
DROP TABLE EMPLOYEE
DROP TABLE PRODUCT
DROP TABLE FLIGHT
DROP TABLE GIFTLIST
DROP TABLE HOTEL
DROP TABLE OUTING
DROP TABLE PREPACKEDTRAVELPACKAGE
DROP TABLE STAGE
DROP TABLE USER_GROUP
